export const localization = {
  en: {
    headerTitleMain: "Main",
    headerTitleTasks: "Tasks",
    headerTitleProfile: "Profile",
    homePageAttraction: 'Attractions',
    homePageRecipes: 'Recipes',
    tasksPageAlphabet: 'Alphabet',
    tasksPageAlphabetDescription: 'Learn letters',
    tasksPageDictionary: 'Dictionary',
    tasksPageDictionaryDescription: 'My learned words',
    tasksPageLearnWords: 'Learning words',
    tasksPageLearnWordsDescription: 'Choose the correct translation of the word',
    tasksPageConstructor: 'Make an offer',
    tasksPageConstructorDescription: 'Make sentences from words',
    tasksPageTest: 'Test',
    tasksPageTests: 'Tests',
    tasksPageTestsDescription: 'Test your knowledge',
    tasksPageGrammar: 'Education',
    tasksPageGrammarDescription: 'Basic rules of the language',
    profileProgressPages: 'Pages read',
    profileProgressLesson: 'Passed lessons',
    profileStatusWord: 'Words learned',
    profileStatusLevel: 'Level',
    profileStatusAchievements: 'My achievements',
    alphabetPage: 'Alphabet',
    alphabetLearnPage: 'Learning',
    alphabetTestPage: 'Test yourself',
    grammarLesson: 'Lesson',
    alphabet: {
      alphabetPage: 'Alphabet',
      learnPage: 'Learning',
      testPage: 'Test yourself'
    }

  },
  tat: {
    headerTitleMain: "Баш бит",
    headerTitleTasks: "Биремнәр",
    headerTitleProfile: "Профиль",
    homePageAttraction: 'Истәлекле урыннар',
    homePageRecipes: 'Рецептлар',
    tasksPageAlphabet: 'Әлифба',
    tasksPageAlphabetDescription: 'Хәрефләр өйрәнәбез',
    tasksPageDictionary: 'Сүзлек',
    tasksPageDictionaryDescription: 'Минем өйрәнгән сүзләрем',
    tasksPageLearnWords: 'Сүзләрне өйрәнәбез',
    tasksPageLearnWordsDescription: 'Сүзнең дөрес тәрҗемәсен сайлагыз',
    tasksPageConstructor: 'Җөмләләр төзү',
    tasksPageConstructorDescription: 'Сүзләрдән җөмләләр төзегез',
    tasksPageTest: 'Тест',
    tasksPageTests: 'Тестлар',
    tasksPageTestsDescription: 'Белемеңне сына',
    tasksPageGrammar: 'Укыту',
    tasksPageGrammarDescription: 'Телнең төп кагыйдәләре',
    profileProgressPages: 'Битләр укылган',
    profileProgressLesson: 'Дәресләр узды',
    profileStatusWord: 'Өйрәнелгән сүзләр',
    profileStatusLevel: 'Уровень',
    profileStatusAchievements: 'Минем казанышларым',
    alphabetPage: 'Әлифба',
    alphabetLearnPage: 'Өйрәнү',
    alphabetTestPage: 'Тикшерү',
    grammarLesson: 'Дәрес',
    alphabet: {
      alphabetPage: 'Әлифба',
      learnPage: 'Өйрәнү',
      testPage: 'Тикшерү'
    }

  },
  ru: {
    headerTitleMain: "Главная",
    headerTitleTasks: "Задания",
    headerTitleProfile: "Профиль",
    homePageAttraction: 'Достопримечательности',
    tasksPageAlphabet: 'Алфавит',
    homePageRecipes: 'Рецепты',
    tasksPageAlphabetDescription: 'Учим буквы',
    tasksPageDictionary: 'Словарь',
    tasksPageDictionaryDescription: 'Мои выученные слова',
    tasksPageLearnWords: 'Учим слова',
    tasksPageLearnWordsDescription: 'Выбери верный перевод слова',
    tasksPageConstructor: 'Составь предложение',
    tasksPageConstructorDescription: 'Собери предложение из слов',
    tasksPageTest: 'Тест',
    tasksPageTests: 'Тесты',
    tasksPageTestsDescription: 'Проверь свои знания',
    tasksPageGrammar: 'Обучение',
    tasksPageGrammarDescription: 'Основные правила языка',
    profileProgressPages: 'Прочитано страниц',
    profileProgressLesson: 'Пройдено уроков',
    profileStatusWord: 'Слов выучил',
    profileStatusLevel: 'Уровень',
    profileStatusAchievements: 'Мои достижения',
    alphabetPage: 'Алфавит',
    alphabetLearnPage: 'Изучение',
    alphabetTestPage: 'Проверить себя',
    grammarLesson: 'Урок',
    alphabet: {
      alphabetPage: 'Алфавит',
      learnPage: 'Изучение',
      testPage: 'Проверить себя'
    }

  }
}