export const CREATE_POST = 'POST/CREATE_POST';
export const FETCH_POSTS = 'POST/FETCH_POSTS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const EDIT_HEADER = 'APP/EDIT_HEADER';
export const EDIT_LOCALIZATION = 'APP/EDIT_LOCALIZATION';
export const LOGIN = 'APP/LOGIN';
export const LOGOUT = 'APP/LOGOUT';